# Generated by Django 3.0.6 on 2020-05-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cowsay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowsaytext',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
